### ISSUE TITLE
Doesn`t work after update to 1.3.2 from 1.3.1

### ISSUE THREAD

**Issue by aulianov** [philbot9/youtube-info#12]
subj

**Comment by philbot9** [comment]
Hi there,

Can you please provide more information?

What are you trying to do? Is there some kind of an error message?

Thanks.

**Comment by aulianov** [comment]
$ npm install youtube-info

var fetchVideoInfo = require('youtube-info');
  fetchVideoInfo({videoId: 'Rb0UmrCXxVA', language: 'ru'}, function (err, videoInfo) {
    if (err) throw new Error(err);
    console.log(videoInfo);
  });

![image](https://user-images.githubusercontent.com/4005431/49495558-6ccbf200-f874-11e8-958e-c3b8d0686872.png)

**Comment by aulianov** [comment]
fetchVideoInfo('Rb0UmrCXxVA', function (err, videoInfo) {
    if (err) throw new Error(err);
    console.log(videoInfo);
  });
==> worked


fetchVideoInfo('Rb0UmrCXxVA', {language: 'ru'}, function (err, videoInfo) {
    if (err) throw new Error(err);
    console.log(videoInfo);
  });
==> not worked

**Comment by philbot9** [comment]
@aulianov I see, the { langauge: 'ru' } parameter is not supported in version 1.3.2, yet. It will be in the next release (currently in progress).
