### ISSUE TITLE
Can it valitate youtube link

### ISSUE THREAD

**Issue by semionvn** [philbot9/youtube-info#6]
Can it valite invalid youtube link before get data?

**Comment by philbot9** [comment]
Hi there,

I'm not sure I understand. Can you give me an example, what you would expect to happen and what actually happens.

Thanks

**Comment by tuanhuu** [comment]
> Hi there,
> 
> I'm not sure I understand. Can you give me an example, what you would expect to happen and what actually happens.
> 
> Thanks

Hi, thank for reply
For example, i paste a link such as a youtube video list, like "https://www.youtube.com/watch?v=ROZGwZ3Raqg&start_radio=1&list=RDMMROZGwZ3Raqg", so cant it get data from it. Or just with single video link, like this "https://www.youtube.com/watch?v=qFLhGq0060w"

**Comment by tuanhuu** [comment]
> Hi there,
> 
> I'm not sure I understand. Can you give me an example, what you would expect to happen and what actually happens.
> 
> Thanks

Hi, thank for reply
For example,  i paste a link such as "https://youtu.be/ROZGwZ3Raqg?list=RDMMROZGwZ3Raqg", so can it get videoID and fetch data from it? Or just with link like this "https://www.youtube.com/watch?v=Dnd5o1NwkLo"

**Comment by philbot9** [comment]
I see. No that's not supported. It only does one video ID at a time. You would have to first extract the IDs from the playlist using cheerio for example, and then you can pass them to this module one at a time.
